# Generated by Django 5.0 on 2024-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(to='Menu.menu'),
        ),
    ]
